# Generated by Django 5.1.1 on 2024-09-07 11:38

import cafe.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('HOT_COFFEE', 'Hot Coffee'), ('COLD_COFFEE', 'Cold Coffee'), ('TEA', 'Tea'), ('SHAWARMA', 'Shawarma'), ('SANDWICH', 'Sandwich'), ('HOT_DOG', 'Hot Dog'), ('ANOTHER_FAST_FOOD', 'Another Fast Food'), ('BAKERY', 'Bakery'), ('ICE_CREAM', 'Ice Cream')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to=cafe.models.movie_image_file_path)),
                ('season_product', models.BooleanField(default=False)),
            ],
        ),
    ]
