# Generated by Django 5.1.1 on 2024-09-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
