# Generated by Django 5.1.1 on 2024-09-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_order_additional_information_order_takeaway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='start',
            new_name='stars',
        ),
    ]
